name: Website Monitor

# Define the workflow to run on a schedule
on:
  schedule:
    - cron: "*/7 * * * *"  # Run every 5 minutes (update interval to match GitHub's constraints)

jobs:
  website-monitor:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Hit websites
    - name: Hit websites
      env:
        URLS: "https://snappedurl.onrender.com/temp"
      run: |
        echo "Starting website monitoring..."
        for url in $(echo $URLS | tr "," "\n"); do
          status=$(curl -o /dev/null -s -w "%{http_code}" $url);
          echo "Request to $url completed with status code: $status";
        done
